// The OpenNext build creates this file before Wrangler bundles the Worker.
// @ts-expect-error generated by `opennextjs-cloudflare build`
import openNextWorker from "./.open-next/worker.js"

type WorkerEnv = {
  CRON_SECRET?: string
  NEXT_PUBLIC_SITE_URL?: string
  SITE_BASE_URL?: string
}

function getInternalCronUrl(env: WorkerEnv): string {
  const baseUrl = env.NEXT_PUBLIC_SITE_URL || env.SITE_BASE_URL || "https://xiaoheiwan-ai-store.local"
  return new URL("/api/cron/daily-report", baseUrl).toString()
}

export default {
  fetch: openNextWorker.fetch,

  async scheduled(_event: ScheduledEvent, env: WorkerEnv, ctx: ExecutionContext) {
    if (!env.CRON_SECRET) {
      console.error("CRON_SECRET is not configured; skipping daily report cron.")
      return
    }

    const request = new Request(getInternalCronUrl(env), {
      headers: {
        authorization: `Bearer ${env.CRON_SECRET}`,
      },
    })

    ctx.waitUntil(
      openNextWorker.fetch(request, env, ctx).then(async (response: Response) => {
        if (!response.ok) {
          console.error("Daily report cron failed", response.status, await response.text())
        }
      }),
    )
  },
}
